// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ExcavateArgs {
    pub x: u32,
    pub y: u32,
    pub z: u32,
}

impl From<ExcavateArgs> for super::Reducer {
    fn from(args: ExcavateArgs) -> Self {
        Self::Excavate {
            x: args.x,
            y: args.y,
            z: args.z,
        }
    }
}

impl __sdk::InModule for ExcavateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `excavate`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait excavate {
    /// Request that the remote module invoke the reducer `excavate` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`excavate:excavate_then`] to run a callback after the reducer completes.
    fn excavate(&self, x: u32, y: u32, z: u32) -> __sdk::Result<()> {
        self.excavate_then(x, y, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `excavate` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn excavate_then(
        &self,
        x: u32,
        y: u32,
        z: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl excavate for super::RemoteReducers {
    fn excavate_then(
        &self,
        x: u32,
        y: u32,
        z: u32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ExcavateArgs { x, y, z }, callback)
    }
}
