// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestWorldChunksArgs {
    pub chunk_ids: Vec<u64>,
}

impl From<RequestWorldChunksArgs> for super::Reducer {
    fn from(args: RequestWorldChunksArgs) -> Self {
        Self::RequestWorldChunks {
            chunk_ids: args.chunk_ids,
        }
    }
}

impl __sdk::InModule for RequestWorldChunksArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_world_chunks`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_world_chunks {
    /// Request that the remote module invoke the reducer `request_world_chunks` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_world_chunks:request_world_chunks_then`] to run a callback after the reducer completes.
    fn request_world_chunks(&self, chunk_ids: Vec<u64>) -> __sdk::Result<()> {
        self.request_world_chunks_then(chunk_ids, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_world_chunks` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_world_chunks_then(
        &self,
        chunk_ids: Vec<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl request_world_chunks for super::RemoteReducers {
    fn request_world_chunks_then(
        &self,
        chunk_ids: Vec<u64>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RequestWorldChunksArgs { chunk_ids }, callback)
    }
}
