// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerTransformArgs {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub pitch: f32,
}

impl From<UpdatePlayerTransformArgs> for super::Reducer {
    fn from(args: UpdatePlayerTransformArgs) -> Self {
        Self::UpdatePlayerTransform {
            x: args.x,
            y: args.y,
            z: args.z,
            yaw: args.yaw,
            pitch: args.pitch,
        }
    }
}

impl __sdk::InModule for UpdatePlayerTransformArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_transform`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_transform {
    /// Request that the remote module invoke the reducer `update_player_transform` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_player_transform:update_player_transform_then`] to run a callback after the reducer completes.
    fn update_player_transform(
        &self,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        pitch: f32,
    ) -> __sdk::Result<()> {
        self.update_player_transform_then(x, y, z, yaw, pitch, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_player_transform` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_player_transform_then(
        &self,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        pitch: f32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_player_transform for super::RemoteReducers {
    fn update_player_transform_then(
        &self,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
        pitch: f32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdatePlayerTransformArgs {
                x,
                y,
                z,
                yaw,
                pitch,
            },
            callback,
        )
    }
}
