// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct World {
    pub id: u8,
    pub seed: u32,
    pub voxel_size: f32,
    pub chunk_size: u32,
    pub world_chunks: u32,
}

impl __sdk::InModule for World {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `World`.
///
/// Provides typed access to columns for query building.
pub struct WorldCols {
    pub id: __sdk::__query_builder::Col<World, u8>,
    pub seed: __sdk::__query_builder::Col<World, u32>,
    pub voxel_size: __sdk::__query_builder::Col<World, f32>,
    pub chunk_size: __sdk::__query_builder::Col<World, u32>,
    pub world_chunks: __sdk::__query_builder::Col<World, u32>,
}

impl __sdk::__query_builder::HasCols for World {
    type Cols = WorldCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            seed: __sdk::__query_builder::Col::new(table_name, "seed"),
            voxel_size: __sdk::__query_builder::Col::new(table_name, "voxel_size"),
            chunk_size: __sdk::__query_builder::Col::new(table_name, "chunk_size"),
            world_chunks: __sdk::__query_builder::Col::new(table_name, "world_chunks"),
        }
    }
}

/// Indexed column accessor struct for the table `World`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldIxCols {
    pub id: __sdk::__query_builder::IxCol<World, u8>,
}

impl __sdk::__query_builder::HasIxCols for World {
    type IxCols = WorldIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for World {}
