// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_chunk_type::WorldChunk;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_chunk`.
///
/// Obtain a handle from the [`WorldChunkTableAccess::world_chunk`] method on [`super::RemoteTables`],
/// like `ctx.db.world_chunk()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_chunk().on_insert(...)`.
pub struct WorldChunkTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldChunk>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_chunk`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldChunkTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldChunkTableHandle`], which mediates access to the table `world_chunk`.
    fn world_chunk(&self) -> WorldChunkTableHandle<'_>;
}

impl WorldChunkTableAccess for super::RemoteTables {
    fn world_chunk(&self) -> WorldChunkTableHandle<'_> {
        WorldChunkTableHandle {
            imp: self.imp.get_table::<WorldChunk>("world_chunk"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldChunkInsertCallbackId(__sdk::CallbackId);
pub struct WorldChunkDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldChunkTableHandle<'ctx> {
    type Row = WorldChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldChunk> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldChunkInsertCallbackId {
        WorldChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldChunkDeleteCallbackId {
        WorldChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldChunkUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldChunkTableHandle<'ctx> {
    type UpdateCallbackId = WorldChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldChunkUpdateCallbackId {
        WorldChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_chunk`,
/// which allows point queries on the field of the same name
/// via the [`WorldChunkIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_chunk().id().find(...)`.
pub struct WorldChunkIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldChunk, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldChunkTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_chunk`.
    pub fn id(&self) -> WorldChunkIdUnique<'ctx> {
        WorldChunkIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldChunkIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldChunk> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldChunk>("world_chunk");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldChunk>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldChunk>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldChunk`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_chunkQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldChunk`.
    fn world_chunk(&self) -> __sdk::__query_builder::Table<WorldChunk>;
}

impl world_chunkQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_chunk(&self) -> __sdk::__query_builder::Table<WorldChunk> {
        __sdk::__query_builder::Table::new("world_chunk")
    }
}
