// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldChunk {
    pub id: u64,
    pub chunk_x: u32,
    pub chunk_z: u32,
    pub lod: u8,
    pub heights: Vec<u16>,
    pub solid_quads: Vec<u32>,
    pub water_quads: Vec<u32>,
    pub revision: u64,
}

impl __sdk::InModule for WorldChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldChunk`.
///
/// Provides typed access to columns for query building.
pub struct WorldChunkCols {
    pub id: __sdk::__query_builder::Col<WorldChunk, u64>,
    pub chunk_x: __sdk::__query_builder::Col<WorldChunk, u32>,
    pub chunk_z: __sdk::__query_builder::Col<WorldChunk, u32>,
    pub lod: __sdk::__query_builder::Col<WorldChunk, u8>,
    pub heights: __sdk::__query_builder::Col<WorldChunk, Vec<u16>>,
    pub solid_quads: __sdk::__query_builder::Col<WorldChunk, Vec<u32>>,
    pub water_quads: __sdk::__query_builder::Col<WorldChunk, Vec<u32>>,
    pub revision: __sdk::__query_builder::Col<WorldChunk, u64>,
}

impl __sdk::__query_builder::HasCols for WorldChunk {
    type Cols = WorldChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldChunkCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_z: __sdk::__query_builder::Col::new(table_name, "chunk_z"),
            lod: __sdk::__query_builder::Col::new(table_name, "lod"),
            heights: __sdk::__query_builder::Col::new(table_name, "heights"),
            solid_quads: __sdk::__query_builder::Col::new(table_name, "solid_quads"),
            water_quads: __sdk::__query_builder::Col::new(table_name, "water_quads"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldChunkIxCols {
    pub id: __sdk::__query_builder::IxCol<WorldChunk, u64>,
}

impl __sdk::__query_builder::HasIxCols for WorldChunk {
    type IxCols = WorldChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldChunkIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldChunk {}
